#!/bin/env bash


OLD_IFS=$IFS
IFS='-'
MUSIC_DIR="$HOME/Music"

if [[ -n "$1" && -d "$1" ]]; then
    MUSIC_DIR=$(realpath "$1")
fi


pushd $MUSIC_DIR >/dev/null

#printf "%s%s %s\n" "$title" "${padding:${#title}}" "Page 1"
ls | while read f; do
    read -ra data <<< "$f"

    title=${data[0]}
    title=${title// /}

    artist=${data[1]}
    artist=${artist// /}
    artist=${artist//.mp3/}  # replace mp3

    # echo "$title"
    # echo "$artist"
    # echo "Editing: $f with: $title -> $artist"
    printf "Editing: %s ...\n" "$f" 
    printf "Patched: %s with %s\n" "$title" "$artist"
    printf "\n"
    eyeD3 --encoding utf8 -t "$title" -a "$artist" "$f" >/dev/null
done

popd >/dev/null

IFS=$OLD_IFS

# vim: set ft=bash:
