#!/bin/env bash

# set -x

if [[ "$#" -ne 1 ]]; then
    echo "Usage: $(basename $0) <proc_name>"
    exit -1
fi

proc_name="$1"

# while read pid;
# do
#     kill -9 "$pid" 2> /dev/null;
# done <<< "$(ps aux | grep ${proc_name} | grep -v grep | awk '{print $2}')"

ps aux | grep $proc_name | grep -v grep | awk '{print $2}' | xargs kill -9


# vim: set ft=bash:
