#!/bin/env bash

# set -x

if [[ "$#" -ne 1 ]]; then
    echo 'No proper process name input.'
    exit -1
fi

proc_name="$1"

while read pid;
do
    kill -9 "$pid" 2> /dev/null;
done <<< "$(ps aux | grep ${proc_name} | grep -v grep | awk '{print $2}')"


# vim: set ft=bash:
