#!/bin/env bash

# trap INT
# find $HOME/Music -type f -name "*.mp3" | shuf | while read f; do ffplay -nodisp -hide_banner "$@" -autoexit -- "$f"; done

# cvlc $HOME/Documents/fav_music.m3u8 --random --verbose 0 --no-metadata-network-access "$@"

PLAY_LIST='/tmp/playlist'

trap "rm -f ${PLAY_LIST}"  QUIT EXIT INT

find $HOME/Music -type f -name "*.mp3" | shuf > ${PLAY_LIST}
mpg123 -z --long-tag -v -@ ${PLAY_LIST}
