#!/usr/bin/env bash

set -e
# PS4='$LINENO: '
# set -xe

CWD=$(dirname $(readlink "$0"))
PAL_ZIP="$CWD/pal.zip"
PAL_DIR="$CWD/c/pal"
PAL_SRC_CONFIG="$CWD/dosbox.pal.conf"
PAL_CONFIG_DIR="$HOME/.pal"

if [[ ! -d "$PAL_DIR" ]]; then

    if [[ ! -f "$PAL_ZIP" ]]; then
        echo 'No pal.zip found, launching abort'
        exit -1
    fi

    if [[ ! -d "$PAL_CONFIG_DIR" ]]; then

        echo "No $PAL_CONFIG_DIR"
        mkdir -p "$PAL_CONFIG_DIR"
        cp -vf "$PAL_SRC_CONFIG" "$PAL_CONFIG_DIR/dosbox.pal.conf"
    fi


    echo 'First time to launch pal, installing...'
    mkdir -p "$PAL_DIR"
    unzip "$PAL_ZIP" -d "$PAL_DIR"
fi

/usr/bin/dosbox -conf "$PAL_CONFIG_DIR/dosbox.pal.conf"
